fix split before definition
```
Ricks-MacBook-Air:hypernode-vagrant vdloo$ vagrant status
/Users/vdloo/code/projects/hypernode-vagrant/Vagrantfile:141:in `block (2 levels) in <top (required)>': undefined method `split' for nil:NilClass (NoMethodError)
```