do not test with ruby 1 9 3 anymore
code coverage test dependency `json` 2.0 dropped support for Ruby 1.9.

```
Fetching: json-2.0.1.gem (100%)
ERROR:  Error installing simplecov:
	json requires Ruby version ~> 2.0.
ERROR:  Error installing coveralls:
	json requires Ruby version ~> 2.0.
```