only print error output if error output
to fix:
```
  File "/tmp/hypernode-vagrant-runner/tools/hypernode-vagrant-runner/hypernode_vagrant_runner/utils.py", line 46, in write_output_to_stdout
    stdout.buffer.write(output)
TypeError: a bytes-like object is required, not 'NoneType'
```